/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports all enum related types from the schema.
 *
 * 🟢 You can import this file directly.
 */

export const TimeOfDayEnum = {
  MORNING: 'MORNING',
  EVENING: 'EVENING',
} as const;

export type TimeOfDayEnum = (typeof TimeOfDayEnum)[keyof typeof TimeOfDayEnum];

export const SubjectEnum = {
  ALGO: 'ALGO',
  FRENCH: 'FRENCH',
  ENGLISH: 'ENGLISH',
  MATH: 'MATH',
  PHYSICS: 'PHYSICS',
  CHEMISTRY: 'CHEMISTRY',
  BIOLOGY: 'BIOLOGY',
  HISTORY: 'HISTORY',
  GEOGRAPHY: 'GEOGRAPHY',
  ECONOMICS: 'ECONOMICS',
  COMPUTER_SCIENCE: 'COMPUTER_SCIENCE',
  SPORT: 'SPORT',
  MANDARIN: 'MANDARIN',
  MUSIC: 'MUSIC',
  SPANISH: 'SPANISH',
  GERMAN: 'GERMAN',
  ITALIAN: 'ITALIAN',
  ARABIC: 'ARABIC',
} as const;

export type SubjectEnum = (typeof SubjectEnum)[keyof typeof SubjectEnum];

export const ElectiveExamEnum = {
  SPANISH: 'SPANISH',
  MUSIC: 'MUSIC',
  ITALIAN: 'ITALIAN',
  MANDARIN: 'MANDARIN',
  MATH: 'MATH',
  GERMAN: 'GERMAN',
} as const;

export type ElectiveExamEnum = (typeof ElectiveExamEnum)[keyof typeof ElectiveExamEnum];

export const MajorEnum = {
  COMPUTER_SCIENCE: 'COMPUTER_SCIENCE',
  MATH: 'MATH',
  SCIENCE: 'SCIENCE',
  LETTRE: 'LETTRE',
  TECHNIQUE: 'TECHNIQUE',
  ECO: 'ECO',
  INFORMATIQUE: 'INFORMATIQUE',
  SPORT: 'SPORT',
} as const;

export type MajorEnum = (typeof MajorEnum)[keyof typeof MajorEnum];

export const TermEnum = {
  PRINCIPAL: 'PRINCIPAL',
  RETAKE: 'RETAKE',
} as const;

export type TermEnum = (typeof TermEnum)[keyof typeof TermEnum];

export const CityEnum = {
  YAOUNDE: 'YAOUNDE',
  DOUALA: 'DOUALA',
  BAMENDA: 'BAMENDA',
  MAROUA: 'MAROUA',
  GAROUA: 'GAROUA',
  KUMBO: 'KUMBO',
} as const;

export type CityEnum = (typeof CityEnum)[keyof typeof CityEnum];

export const Role = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  ADMIN: 'ADMIN',
} as const;

export type Role = (typeof Role)[keyof typeof Role];

export const Status = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  DISABLED: 'DISABLED',
  DELETED: 'DELETED',
} as const;

export type Status = (typeof Status)[keyof typeof Status];

export const MediaStatus = {
  PENDING: 'PENDING',
  CONFIRMED: 'CONFIRMED',
  DELETED: 'DELETED',
  FAILED: 'FAILED',
} as const;

export type MediaStatus = (typeof MediaStatus)[keyof typeof MediaStatus];

export const ProductStatus = {
  AVAILABLE: 'AVAILABLE',
  OUT_OF_STOCK: 'OUT_OF_STOCK',
  DISCONTINUED: 'DISCONTINUED',
} as const;

export type ProductStatus = (typeof ProductStatus)[keyof typeof ProductStatus];
