@baseUrl = http://localhost:10000/api



### 
# @name create-notification
POST {{baseUrl}}/notification
Content-Type: application/json

{
    "title": "Notification Title",
    "description": "Notification Message",
    "schedule": {
        "scheduleType": "DELAYED",
        "delaySeconds": 1
    },
    "recipients": {
        "type": "ALL"
    },
    "payload": {
        "en": {
            "language": "en",
            "title": "Notification Test",
            "content": "Notification Message Test",
            "data": "Notification Data"
        },
        "fr": {
            "language": "fr",
            "title": "Titre de la notification",
            "content": "Message de la notification",
            "data": "Données de la notification"
        },

        "ar": {
            "language": "ar",
            "title": "عنوان الإشعار",
            "content": "رسالة الإشعار",
            "data": "بيانات الإشعار"
        }
    }
}
