@apiKey = AIzaSyBoFeoCUvczJXVp2FhWYm26UiSGjmYLqOo
@firebaseUrl = https://identitytoolkit.googleapis.com/v1


@baseUrl = http://localhost:10000/api

@AdminEmail = tigana139997@gmail.com
@AdminPassword = 12345678


########################################
# AUTH FLOW: ADMIN LOGIN
########################################


### 
# @name firebase_login
POST {{firebaseUrl}}/accounts:signInWithPassword?key={{apiKey}}
Content-Type: application/json

{
  "email": "{{AdminEmail}}",
  "password": "{{AdminPassword}}",
  "returnSecureToken": true
}


###
# @name serverLogin
POST {{baseUrl}}/auth/password
Content-Type: application/json

{
    "token": "{{firebase_login.response.body.idToken}}"
}


