@apiKey = AIzaSyDWKplAl5Vp43pG0j5j3vnThRJIPwv1E44
@firebaseUrl = https://identitytoolkit.googleapis.com/v1

@baseUrl = http://localhost:10000/api

@email = tigana137@gmail.com
@password = 12345678
@schoolOwnerEmail = test5@gmail.com
@schoolOwnerPassword = 12345678

###########################
# 1- create school with user as super admin
###########################

###
# @name firebaseLogin
POST {{firebaseUrl}}/accounts:signInWithPassword?key={{apiKey}}
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}",
  "returnSecureToken": true
}


###
# @name createSchoolWithUser
POST {{baseUrl}}/schools/with-user
Content-Type: application/json
Authorization: Bearer {{firebaseLogin.response.body.idToken}}

{
  "user": {
    "username": "school1",
    "email": "{{schoolOwnerEmail}}",
    "password": "{{schoolOwnerPassword}}"
  },
  "school": {
    "name": "School 1",
    "publicId": "school1-public-id",
    "city": "SOUSSE"
  }
}


###########################
# 2- login to the created user and verify it has a school and updated it 
###########################

###
# @name firebaseLogin
POST {{firebaseUrl}}/accounts:signInWithPassword?key={{apiKey}}
Content-Type: application/json

{
  "email": "{{schoolOwnerEmail}}",
  "password": "{{schoolOwnerPassword}}",
  "returnSecureToken": true
}

###
# @name getMySchool
GET {{baseUrl}}/schools/me
Content-Type: application/json
Authorization: Bearer {{firebaseLogin.response.body.idToken}}


###
# @name updateMySchool
PUT {{baseUrl}}/schools/{{getMySchool.response.body.id}}
Content-Type: application/json
Authorization: Bearer {{firebaseLogin.response.body.idToken}}

{
  "name": "School 1 Updated",
  "publicId": "school1-public-id-updated",
  "city": "MONASTIR"
}


###########################
# 3- create school with user as school admin
###########################
@email01 = test01@gmail.com
@password01 = 12345678


### 
# @name firebase_signup
POST {{firebaseUrl}}/accounts:signUp?key={{apiKey}}
Content-Type: application/json

{
  "email": "{{email01}}",
  "password": "{{password01}}",
  "returnSecureToken": true
}


###
# @name firebaseLogin
POST {{firebaseUrl}}/accounts:signInWithPassword?key={{apiKey}}
Content-Type: application/json

{
  "email": "{{email01}}",
  "password": "{{password01}}",
  "returnSecureToken": true
}

### 
# @name serverSignup
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
    "token": "{{firebaseLogin.response.body.idToken}}"
}


###
# @name serverLogin
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "token": "{{firebaseLogin.response.body.idToken}}"
}


###
# @name createMySchool
POST {{baseUrl}}/schools
Content-Type: application/json
Authorization: Bearer {{firebaseLogin.response.body.idToken}}

{
  "name": "School 2",
  "publicId": "school2-public-id",
  "city": "SOUSSE"
}


