@apiKey = AIzaSyDWKplAl5Vp43pG0j5j3vnThRJIPwv1E44
@firebaseUrl = https://identitytoolkit.googleapis.com/v1

@baseUrl = http://localhost:10000/api

@email = tigana137@gmail.com
@password = 12345678

###
# @name login
POST {{firebaseUrl}}/accounts:signInWithPassword?key={{apiKey}}
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}",
  "returnSecureToken": true
}


### 
# @name get-users
GET {{baseUrl}}/users
Content-Type: application/json
